# Generated by Django 2.0.8 on 2018-09-24 16:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Shipment type')),
                ('image', models.ImageField(upload_to='', verbose_name='Shipment photo')),
                ('weight', models.IntegerField(verbose_name='Shipment weight KG')),
                ('dimension', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('is_delivered', models.CharField(max_length=255, verbose_name='')),
            ],
        ),
    ]
