# Generated by Django 2.0.8 on 2018-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20190924_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='shipment',
            name='height_dimesion',
            field=models.IntegerField(default=0, verbose_name='height'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='width_dimesion',
            field=models.IntegerField(default=0, verbose_name='width'),
            preserve_default=False,
        ),
    ]
