# Generated by Django 2.0.8 on 2018-09-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_country', models.CharField(max_length=30, verbose_name='Trip location Country')),
                ('to_country', models.CharField(max_length=30, verbose_name='Trip Destination Country')),
                ('from_city', models.CharField(max_length=30, verbose_name='Trip location City')),
                ('to_city', models.CharField(max_length=30, verbose_name='Trip Destination City')),
                ('departure_time', models.DateTimeField(verbose_name='Departure Time')),
            ],
        ),
    ]
